version: "3"

services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    networks:
      project:
        aliases:
          - ${NGINX_ALIAS}
    environment:
      SERVER_NAME: ${NGINX_ALIAS}
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
      - php-fpm

  node:
    build: .docker/node
    networks:
      - project
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

  php-fpm:
    build:
      context: .docker/php
      target: fpm
    networks:
      - project
    command: [ "php-fpm" ]
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    networks:
      - project
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "${MAILHOG_PORT}:8025"
    networks:
      - project

  redis:
    image: redis:6-alpine
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - project
    volumes:
      - redis-data:/data

  worker:
    build:
      context: .docker/php
      target: worker
    networks:
      - project
    volumes:
      - ./:/var/www/html
    depends_on:
      - php-fpm
    restart: unless-stopped
